### ISSUE TITLE
[AMA] Create Login Page

### ISSUE THREAD

**Issue by BT-Creator** [osoc24/loama#25]
# Login
- [ ] Write Vue components
- [ ] Send login details to controller
- [ ] Redirect on successful login

# Keep in mind
- When the login is not successful, make sure to show an appropriate error message
- Make the components as atomic as possible
- The login screen will be shared between AMA and Demo apps, so try to make things like title, etc... as generic as possible and customizable by prop

**Comment by Zelzahn** [comment]
## Shortcut

The sidebar can be considered nice-to-have, so after fixing the colours it's ready for review.
